[Tidal]
token_type=Bearer
access_token=
refresh_token=

[GUI]
enabled=true
systray_enabled=false
display_cover_background=true
display_cover_foreground=true

[Exporter_smb]
enabled=false
server=
share=
password=
username=
workgroup=
cache=false

[CMD_EVENTS]
; Commands executed via sh -c on various events
on_save=touch /tmp/woodaudio_config_saved
; on_track_change=touch /tmp/woodaudio_track_changed
; on_like=touch /tmp/woodaudio_track_liked