import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

import "./static/NotoSans_Condensed-Light.ttf";
import "./static/NotoSans_Condensed-SemiBold.ttf";

export global Data {
    in property <bool> is_session_exist;
    in property <bool> is_loading;
    in property <image> session_qrcode;
    in property <string> session_code;

    in property <string> current_track_name;
    in property <string> current_album_name;
    in property <string> current_artist_name;

    in property <image> current_cover_foreground;
    in property <image> current_cover_background;

    in property <string> current_duration;
    in property <string> current_track_duration;
    in property <percent> current_duration_percentage;

    in property <int> window_x;
    in property <int> window_y;

    out property <float> window_x_ratio: window_x / 1024;
    out property <float> window_y_ratio: window_y / 600;

    callback request_new_value();
    callback request_next_track();
}

component TextShadow {
    in property <string> text;
    in property <bool> is-bold: false;
    in property <length> font-size: 32px;
    in property <TextHorizontalAlignment> horizontal-alignment: center;
    in property <TextVerticalAlignment> vertical-alignment: center;

    Text {
        text: text;
        font-family: "Noto Sans Condensed";
        font-weight: is-bold ? 800 : 400;
        font-size: font-size;
        x: is-bold ? 2px : 1px;
        y: is-bold ? 2px : 1px;
        color: black;
        horizontal-alignment: horizontal-alignment;
        vertical-alignment: vertical-alignment;
    }
    Text {
        text: text;
        font-family: "Noto Sans Condensed";
        font-weight: is-bold ? 800 : 400;
        font-size: font-size;
        x: 0px;
        y: 0px;
        color: white;
        horizontal-alignment: horizontal-alignment;
        vertical-alignment: vertical-alignment;
    }
}

component Player {
    TextShadow {
        text: "\{Data.current_track_name}";
        is-bold: true;
        font-size: 48px * Data.window_x_ratio;
        x: 32px * Data.window_x_ratio;
        y: 24px * Data.window_y_ratio;
    }

    TextShadow {
        text: "\{Data.current_artist_name} - \{Data.current_album_name}";
        font-size: 32px * Data.window_x_ratio;
        x: 32px * Data.window_x_ratio;
        y: 88px * Data.window_y_ratio;
    }

    Rectangle {
        width: 320px * Data.window_x_ratio;
        height: 320px * Data.window_x_ratio;
        x: 352px * Data.window_x_ratio;
        y: 172px * Data.window_y_ratio;
        drop-shadow-color: black;
        drop-shadow-blur: 25px;
        opacity: 0.7;
    }

    Image {
        source: Data.current_cover_foreground;
        width: 320px * Data.window_x_ratio;
        height: 320px * Data.window_x_ratio;
        x: 352px * Data.window_x_ratio;
        y: 172px * Data.window_y_ratio;
    }

    Rectangle {
        background: black;
        opacity: 0.3;
        height: 3px;
        width: 600px * Data.window_x_ratio;
        x: 213px * Data.window_x_ratio;
        y: 541px * Data.window_y_ratio;
    }
    Rectangle {
        background: white;
        height: 5px;
        width: 600px * Data.current_duration_percentage * 100 * Data.window_x_ratio;
        x: 212px * Data.window_x_ratio;
        y: 540px * Data.window_y_ratio;
    }

    TextShadow {
        text: "\{Data.current_duration}";
        is-bold: true;
        font-size: 14px;
        horizontal-alignment: center;
        vertical-alignment: center;
        x: 150px * Data.window_x_ratio;
        y: 532px * Data.window_y_ratio;
        width: 62px;
    }

    TextShadow {
        text: "\{Data.current_track_duration}";
        is-bold: true;
        font-size: 14px;
        horizontal-alignment: center;
        vertical-alignment: center;
        x: 837px * Data.window_x_ratio;
        y: 532px * Data.window_y_ratio;
        width: 62px;
    }
}

component Session {
    VerticalBox {
        alignment: LayoutAlignment.start;

        Text {
            text: "Hello in Woodaudio player!";
            font-family: "Noto Sans Condensed";
            font-weight: 800;
            font-size: 48px * Data.window_x_ratio;
        }
        Text {
            text: "Login to Tidal via: \{Data.session_code}";
            font-family: "Noto Sans Condensed";
            font-size: 32px * Data.window_x_ratio;
        }
        Image {
            source: Data.session_qrcode;
            width: 300px;
            height: 300px;
        }
    }
}

component Loading {
    TextShadow {
        text: "Loading...";
        is-bold: true;
        font-size: 48px * Data.window_x_ratio;
        x: 32px * Data.window_x_ratio;
        y: 24px * Data.window_y_ratio;
    }
}

export component AppWindow inherits Window {
    background: black;

    Image {
        width: 1024px * Data.window_x_ratio;
        height: 1024px * Data.window_x_ratio;
        x: 0;
        y: -212px * Data.window_y_ratio;
        horizontal-alignment: center;
        source: Data.current_cover_background;
    }

    Player {
        visible: !Data.is_loading && Data.is_session_exist;
        x: 0;
        y: 0;
    }
    SwipeGestureHandler {
        handle-swipe-left: true;
        swiped => {
            Data.request_next_track();
        }
    }

    Loading {
        visible: Data.is_session_exist && Data.is_loading;
        x: 0;
        y: 0;
    }

    Session {
        visible: !Data.is_session_exist;
    }

    Timer {
        interval: 15ms;
        running: true;
        triggered => {
            Data.request_new_value();
        }
    }
}
